### ISSUE TITLE
Rename JS file

### ISSUE THREAD

**Issue by luke-m** [imagitama/nodelist-foreach-polyfill#4]
The JS file of this package is called `index.js`, super generic. In some frameworks, all package scripts get put into the same place and then there could be a clash with another file called `index.js`, because it's so generic. So it would be a good idea to rename the JS file to `nodelist-foreach-polyfill.js` or something.

**Comment by zebapy** [comment]
you should use a bundler instead of manually downloading files

**Comment by mitikov** [comment]
@luke-m Is it still actual or you are good with @zebapy suggestion?

Thanks.

**Comment by luke-m** [comment]
The framework my company uses only bundles during the build process. While serving the preview, the files are stored individually, leading to the problem. I opened a ticket for our framework to change this behaviour. I think you can close this issue here because it's more of a problem with our product than with yours. Thanks for replying! :)
